### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by unmanagedtn** [codeforkjeff/simplesign#1]
pi@raspberrypi:~/simplesign $ ./simplesign.py -d /dev/ttyUSB0 -p 8282
2020-03-24 00:17:12,348:ERROR:ERROR: Could not find module 'sample': No module named sample
pi@raspberrypi:~/simplesign $

I dont understand the above error what is simple module is this a python incompatibility ?

**Comment by codeforkjeff** [comment]
You need to specify -m and a config module. 

To use the config-sample.py configuration, run:
```
./simplesign.py -m config-sample -d /dev/ttyUSB0 -p 8282
```

**Comment by unmanagedtn** [comment]
my fault needed to RTFM not tldr
